server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres


  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
